server:
  port: 8082

spring:
  cloud:
    stream:
      kafka: # 如果用的是 rabbitMQ 這裡填 rabbit
        binder:
          brokers: # 訊息中間件服務位址
            - localhost:9092
        bindings:
          myInput:
            consumer:
              autoCommitOffset: false
      bindings:
        myInput: # 通道名稱
          destination: topic2 # 訊息發送的目的地，對應 topic
          group: myGroup # 對應 kafka 的 group
          contentType: application/json # 訊息格式
        myOutput:
          destination: topic1
          contentType: application/json
#        error:
#          destination: myErrors
